### ISSUE TITLE
Incorrect example in the documentation

### ISSUE THREAD

**Issue by amhamid** [pezra/exhal#47]
There is an incorrect example in the documentation, that can cause users have difficulties in using it. 
See my pull request: #46 

## Details
1. Instead of this:
```elixir
iex> doc = ExHal.client
...> |> ExHal.Client.add_headers("User-Agent": "MyClient/1.0")
...> |> ExHal.Client.get("http://example.com/hal")
%ExHal.Document{...}
```

==> You need to pattern match like this, so that your next example to follow_link will work fine:
```elixir
{:ok, doc} = ExHal.client
...> |> ExHal.Client.add_headers("User-Agent": "MyClient/1.0")
...> |> ExHal.Client.get("http://example.com/hal")
%ExHal.Document{...}
```

2. Also here, instead of:
```elixir
iex> ExHal.follow_link("self")
```

==> Should be this:
```elixir
iex> ExHal.follow_link(doc, "self")
```

**Comment by pezra** [comment]
Fixed by #46. Thanks.
